### ISSUE TITLE
Sempress: Fatal errors

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5641]
There's been fatal errors related to this theme today:

p1646820303924869-slack-C4N88L95W

```
[09-Mar-2022 10:07:07 UTC] Fatal error: Uncaught Error: Object of class WP_Error could not be converted to string in /home/wpcom/public_html/wp-content/themes/pub/sempress/content.php:55
Stack trace:
#0 /home/wpcom/public_html/wp-content/themes/pub/sempress/content.php(55): printf('Tagged %1$s', Object(WP_Error))
#1 /home/wpcom/public_html/wp-includes/template.php(772): require('/home/wpcom/pub...')
#2 /home/wpcom/public_html/wp-includes/template.php(716): load_template('/home/wpcom/pub...', false, Array)
#3 /home/wpcom/public_html/wp-includes/general-template.php(204): locate_template(Array, true, false, Array)
#4 /home/wpcom/public_html/wp-content/themes/pub/sempress/index.php(30): get_template_part('content', '')
#5 /home/wpcom/public_html/wp-includes/template-loader.php(106): include('/home/wpcom/pub...')
#6 /home/wpcom/public_html/wp-blog-header.php(19): require_once('/home/wpcom/pub...')
#7 /home/wpcom/public_html/index.php(17): require('/home/wpcom/pub...')
#8 {main}
  thrown in /home/wpcom/public_html/wp-content/themes/pub/sempress/content.php on line 55  []
```

**Comment by jffng** [comment]
Patch here: D76365-code
