### ISSUE TITLE
Radcliffe 2: conflict with Activity Pub plugin on Atomic sites

### ISSUE THREAD

**Issue by liviopv** [Automattic/themes#7776]
### Quick summary

When the Activity Pub plugin and Radcliffe 2 are active, opening the Customizer triggers a fatal error:

```
PHP Fatal error:  Uncaught Error: Attempt to assign property "transport" on null in /wordpress/themes/pub/radcliffe-2/inc/customizer.php:16
Stack trace:
#0 /wordpress/core/6.5.2/wp-includes/class-wp-hook.php(324): radcliffe_2_customize_register(Object(WP_Customize_Manager))
#1 /wordpress/core/6.5.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/6.5.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /wordpress/core/6.5.2/wp-includes/class-wp-customize-manager.php(942): do_action('customize_regis...', Object(WP_Customize_Manager))
#4 /wordpress/core/6.5.2/wp-includes/class-wp-hook.php(324): WP_Customize_Manager->wp_loaded('')
#5 /wordpress/core/6.5.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/core/6.5.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/core/6.5.2/wp-settings.php(717): do_action('wp_loaded')
#8 /srv/htdocs/wp-config.php(81): require_once('/wordpress/core...')
#9 /wordpress/core/6.5.2/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#10 /wordpress/core/6.5.2/wp-admin/admin.php(34): require_once('/wordpress/core...')
#11 /wordpress/core/6.5.2/wp-admin/customize.php(13): require_once('/wordpress/core...')
#12 {main}
  thrown in /wordpress/themes/pub/radcliffe-2/inc/customizer.php on line 16
```

It's reproducible only on Radcliffe 2. Other classic themes (tested T19, Baskerville 2, Astra) work just fine with Activity Pub active

cc @pfefferle 

### Steps to reproduce

1. Activate Radcliffe 2
2. Activate https://wordpress.org/plugins/activitypub/
3. Access Appearance > Customizer

### What you expected to happen

Customizer should load without issues

### What actually happened

Fatal error

### Browser

Google Chrome/Chromium

### Context

Customer report

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Deactivate Activity Pub

**Comment by pfefferle** [comment]
@liviopv the issue seems to be, that ActivityPub sets `custom-header` theme support.

https://github.com/Automattic/wordpress-activitypub/blob/f6b4783dedbc5ad07c42a9c49a275ecaed05a227/includes/class-activitypub.php#L346
